language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "libssl-dev"
      - "wget"
      - "unzip"
      - "libsqlite3-dev"
      - "libxml2-dev"
      - "libxslt1-dev"
      - "redis-server"

sudo: required

os: linux
dist: bionic

# command to install dependencies
install:
  - python3 --version
  #- sudo ln -s $(which python3) /usr/bin/python3.6
  - sudo python3.6 -m pip install setuptools
  - sudo python3.6 -m pip install -r requirements.txt
  - make install

# command to run tests
script:
  - make install
  - cp -r test /opt/botjagwar/test
  - cp -r conf/test_config.ini /opt/botjagwar/conf/config.ini
  - make prepare_tests
  - sudo python3.6 -m pip install nose
  - PYWIKIBOT2_NO_USER_CONFIG=1 sudo python3.6 -m "nose" -v /opt/botjagwar/test
  - make uninstall
