language: python
python:
  - "3.6"
sudo: enabled
os: linux
# command to install dependencies
install:
  - make prepare
  - pip install -r requirements.txt
  - make install
# command to run tests
script:
  - make install
  - make tests # or py.test for Python versions 3.5 and below