language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "libssl-dev"
      - "wget"
      - "unzip"
      - "libsqlite3-dev"
      - "libxml2-dev"
      - "libxslt1-dev"
      - "redis-server"

sudo: required

os: linux
dist: bionic

# command to install dependencies
install:
  - python3 --version
  - sudo python3 -m pip install setuptools
  - sudo python3 -m pip install -r requirements.txt

# command to run tests
script:
  - cp -r conf/test_config.ini conf/config.ini
  - cp -r test /opt/botjagwar/test
  - NORUN=1 bash -xe test.sh
  - PYWIKIBOT2_NO_USER_CONFIG=1 sudo python3 -m "nose" -v /opt/botjagwar/test
  - make uninstall
