-- Migration 007: Track immutable entry creation and Malagasy translation activity.

BEGIN;

ALTER TABLE public.word
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;

DROP TRIGGER IF EXISTS enforce_word_created_at ON public.word;

ALTER TABLE public.word
    ALTER COLUMN created_at SET DEFAULT statement_timestamp();

CREATE OR REPLACE FUNCTION public.enforce_word_created_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := statement_timestamp();
    ELSIF NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'word.created_at is immutable'
            USING ERRCODE = '22000';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER enforce_word_created_at
BEFORE INSERT OR UPDATE OF created_at ON public.word
FOR EACH ROW
EXECUTE FUNCTION public.enforce_word_created_at();

CREATE INDEX IF NOT EXISTS idx_word_created_at
    ON public.word (created_at)
    WHERE created_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.events_malagasy_translation_created (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id bigint NOT NULL,
    definition_id bigint NOT NULL,
    source_language character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT statement_timestamp(),
    cause text NOT NULL CHECK (
        cause IN (
            'dictionary_insert',
            'dictionary_update',
            'definition_reclassified'
        )
    )
);

DROP TRIGGER IF EXISTS protect_malagasy_translation_events
    ON public.events_malagasy_translation_created;
DROP TRIGGER IF EXISTS protect_malagasy_translation_events_truncate
    ON public.events_malagasy_translation_created;

CREATE UNIQUE INDEX IF NOT EXISTS uq_malagasy_translation_event
    ON public.events_malagasy_translation_created (
        word_id,
        definition_id,
        created_at,
        cause
    );

CREATE INDEX IF NOT EXISTS idx_malagasy_translation_event_period
    ON public.events_malagasy_translation_created (
        created_at,
        source_language,
        word_id
    );

CREATE OR REPLACE FUNCTION public.capture_malagasy_translation_link()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    source_language character varying(10);
    target_language character varying(6);
BEGIN
    IF TG_OP = 'UPDATE'
       AND NEW.word IS NOT DISTINCT FROM OLD.word
       AND NEW.definition IS NOT DISTINCT FROM OLD.definition THEN
        RETURN NEW;
    END IF;

    SELECT words.language, definitions.definition_language
    INTO source_language, target_language
    FROM public.word AS words
    CROSS JOIN public.definitions AS definitions
    WHERE words.id = NEW.word
      AND definitions.id = NEW.definition;

    IF source_language <> 'mg' AND target_language = 'mg' THEN
        INSERT INTO public.events_malagasy_translation_created (
            word_id,
            definition_id,
            source_language,
            created_at,
            cause
        ) VALUES (
            NEW.word,
            NEW.definition,
            source_language,
            statement_timestamp(),
            CASE WHEN TG_OP = 'INSERT' THEN 'dictionary_insert' ELSE 'dictionary_update' END
        );
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS capture_malagasy_translation_link ON public.dictionary;
CREATE TRIGGER capture_malagasy_translation_link
AFTER INSERT OR UPDATE OF word, definition ON public.dictionary
FOR EACH ROW
EXECUTE FUNCTION public.capture_malagasy_translation_link();

CREATE OR REPLACE FUNCTION public.capture_reclassified_malagasy_definition()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF NEW.definition_language = 'mg'
       AND OLD.definition_language IS DISTINCT FROM 'mg' THEN
        INSERT INTO public.events_malagasy_translation_created (
            word_id,
            definition_id,
            source_language,
            created_at,
            cause
        )
        SELECT
            links.word,
            NEW.id,
            words.language,
            statement_timestamp(),
            'definition_reclassified'
        FROM public.dictionary AS links
        JOIN public.word AS words ON words.id = links.word
        WHERE links.definition = NEW.id
          AND words.language <> 'mg';
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS capture_reclassified_malagasy_definition ON public.definitions;
CREATE TRIGGER capture_reclassified_malagasy_definition
AFTER UPDATE OF definition_language ON public.definitions
FOR EACH ROW
EXECUTE FUNCTION public.capture_reclassified_malagasy_definition();

CREATE OR REPLACE FUNCTION public.protect_malagasy_translation_events()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF TG_OP = 'INSERT' AND pg_trigger_depth() > 1 THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'Malagasy translation events are append-only and trigger-managed'
        USING ERRCODE = '42501';
END;
$function$;

CREATE TRIGGER protect_malagasy_translation_events
BEFORE INSERT OR UPDATE OR DELETE ON public.events_malagasy_translation_created
FOR EACH ROW
EXECUTE FUNCTION public.protect_malagasy_translation_events();

CREATE TRIGGER protect_malagasy_translation_events_truncate
BEFORE TRUNCATE ON public.events_malagasy_translation_created
FOR EACH STATEMENT
EXECUTE FUNCTION public.protect_malagasy_translation_events();

REVOKE ALL ON TABLE public.events_malagasy_translation_created FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.events_malagasy_translation_created_id_seq FROM PUBLIC;
GRANT SELECT ON TABLE public.events_malagasy_translation_created TO botjagwar;

CREATE OR REPLACE FUNCTION public.atlas_dashboard_statistics(
    p_language_limit integer DEFAULT 8
)
RETURNS TABLE (
    period text,
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    entry_count bigint,
    translated_languages jsonb,
    generated_at timestamp with time zone,
    missing_timestamp_count bigint
)
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = pg_catalog, public
AS $function$
    WITH clock AS (
        SELECT
            current_timestamp AS as_of,
            date_trunc('week', current_timestamp AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' AS week_start,
            date_trunc('month', current_timestamp AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' AS month_start,
            date_trunc('year', current_timestamp AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' AS year_start,
            least(greatest(COALESCE(p_language_limit, 8), 1), 25) AS language_limit
    ), bounds (period, sort_order, period_start, period_end) AS (
        SELECT 'last_day', 1, as_of - interval '1 day', as_of FROM clock
        UNION ALL
        SELECT 'last_7_days', 2, as_of - interval '7 days', as_of FROM clock
        UNION ALL
        SELECT 'last_week', 3, week_start - interval '1 week', week_start FROM clock
        UNION ALL
        SELECT 'last_month', 4, month_start - interval '1 month', month_start FROM clock
        UNION ALL
        SELECT 'year_to_date', 5, year_start, as_of FROM clock
        UNION ALL
        SELECT 'last_year', 6, year_start - interval '1 year', year_start FROM clock
    ), entry_counts AS (
        SELECT bounds.period, count(words.id) AS entry_count
        FROM bounds
        LEFT JOIN public.word AS words
          ON (
              words.created_at >= bounds.period_start
              AND words.created_at < bounds.period_end
          ) OR (
              words.created_at IS NULL
              AND words.date_changed >= bounds.period_start
              AND words.date_changed < bounds.period_end
          )
        GROUP BY bounds.period
    ), translated_counts AS (
        SELECT
            bounds.period,
            events.source_language AS language,
            languages.english_name,
            languages.malagasy_name,
            count(DISTINCT events.word_id) AS translated_entries
        FROM bounds
        JOIN public.events_malagasy_translation_created AS events
          ON events.created_at >= bounds.period_start
         AND events.created_at < bounds.period_end
        LEFT JOIN public.language AS languages ON languages.iso_code = events.source_language
        GROUP BY bounds.period, events.source_language, languages.english_name, languages.malagasy_name
    ), ranked_languages AS (
        SELECT
            translated_counts.*,
            row_number() OVER (
                PARTITION BY translated_counts.period
                ORDER BY translated_counts.translated_entries DESC, translated_counts.language
            ) AS language_rank
        FROM translated_counts
    ), language_lists AS (
        SELECT
            bounds.period,
            COALESCE(
                jsonb_agg(
                    jsonb_build_object(
                        'language', ranked_languages.language,
                        'english_name', ranked_languages.english_name,
                        'malagasy_name', ranked_languages.malagasy_name,
                        'translated_entries', ranked_languages.translated_entries
                    ) ORDER BY ranked_languages.language_rank
                ) FILTER (WHERE ranked_languages.language_rank <= clock.language_limit),
                '[]'::jsonb
            ) AS translated_languages
        FROM bounds
        CROSS JOIN clock
        LEFT JOIN ranked_languages ON ranked_languages.period = bounds.period
        GROUP BY bounds.period
    ), missing_timestamps AS (
        SELECT count(*) AS missing_timestamp_count
        FROM public.word
        WHERE created_at IS NULL
          AND date_changed IS NULL
    )
    SELECT
        bounds.period,
        bounds.period_start,
        bounds.period_end,
        entry_counts.entry_count,
        language_lists.translated_languages,
        clock.as_of AS generated_at,
        missing_timestamps.missing_timestamp_count
    FROM bounds
    JOIN entry_counts ON entry_counts.period = bounds.period
    JOIN language_lists ON language_lists.period = bounds.period
    CROSS JOIN clock
    CROSS JOIN missing_timestamps
    ORDER BY bounds.sort_order;
$function$;

REVOKE ALL ON FUNCTION public.atlas_dashboard_statistics(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.atlas_dashboard_statistics(integer) TO botjagwar;

COMMENT ON COLUMN public.word.created_at IS
    'Database-generated immutable creation time. Legacy rows may use date_changed as a dashboard fallback.';
COMMENT ON TABLE public.events_malagasy_translation_created IS
    'Append-only events for non-Malagasy words acquiring Malagasy definitions.';

NOTIFY pgrst, 'reload schema';

COMMIT;
