[program:translator_1]
command=/opt/ctranslate/venv/bin/python /opt/ctranslate/ctranslate-lite.py 8886
stdout_logfile=/opt/ctranslate/translator_1_stdout.log
stderr_logfile=/opt/ctranslate/translator_1_stderr.log
autostart=true
startretries=10
user=user
stderr_logfile_maxbytes=10MB

[program:translator_2]
command=/opt/ctranslate/venv/bin/python /opt/ctranslate/ctranslate-lite.py 8887
stdout_logfile=/opt/ctranslate/translator_2_stdout.log
stderr_logfile=/opt/ctranslate/translator_2_stderr.log
autostart=true
startretries=10
user=user
stderr_logfile_maxbytes=10MB

[program:translator_3]
command=/opt/ctranslate/venv/bin/python /opt/ctranslate/ctranslate-lite.py 8888
stdout_logfile=/opt/ctranslate/translator_3_stdout.log
stderr_logfile=/opt/ctranslate/translator_3_stderr.log
autostart=true
startretries=10
user=user
stderr_logfile_maxbytes=10MB
