"""PostgreSQL integration tests for Atlas statistics migrations 006 through 011."""

from __future__ import annotations

import os
import uuid
from collections.abc import Callable, Iterator
from contextlib import AbstractContextManager, contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import NoReturn

import psycopg2
import pytest
from psycopg2 import sql
from psycopg2.extensions import connection


PROJECT_ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS = {
    6: PROJECT_ROOT / "data/migrations/006_add_atlas_dashboard_statistics.sql",
    7: PROJECT_ROOT / "data/migrations/007_track_entry_and_translation_creation.sql",
    8: PROJECT_ROOT / "data/migrations/008_add_atlas_dashboard_statistics_mv.sql",
    9: PROJECT_ROOT / "data/migrations/009_backfill_dashboard_translation_events.sql",
    10: PROJECT_ROOT / "data/migrations/010_add_page_check_statistics_snapshots.sql",
    11: PROJECT_ROOT / "data/migrations/011_score_good_page_check_jobs.sql",
}
BASE_SCHEMA = """
CREATE TABLE public.language (
    iso_code character varying(7) PRIMARY KEY,
    english_name character varying(100),
    malagasy_name character varying(100),
    language_ancestor character varying(6)
);
CREATE TABLE public.word (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_changed timestamp with time zone,
    word character varying(150),
    language character varying(10),
    part_of_speech character varying(15)
);
CREATE TABLE public.definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_changed timestamp with time zone,
    definition character varying(1000),
    definition_language character varying(6)
);
CREATE TABLE public.dictionary (
    word bigint REFERENCES public.word(id),
    definition bigint REFERENCES public.definitions(id)
);
CREATE TABLE public.new_associations (
    word bigint NOT NULL REFERENCES public.word(id),
    definition bigint NOT NULL REFERENCES public.definitions(id),
    associated_on timestamp with time zone,
    status text NOT NULL DEFAULT 'PENDING'
);
GRANT USAGE ON SCHEMA public TO botjagwar;
GRANT SELECT ON public.word, public.definitions, public.dictionary,
    public.language, public.new_associations TO botjagwar;
"""

DatabaseFactory = Callable[[int, str], AbstractContextManager[connection]]


def _postgres_unavailable(reason: str) -> NoReturn:
    """Skip unavailable local PostgreSQL or fail when CI requires it."""
    if os.getenv("BOTJAGWAR_REQUIRE_POSTGRES_TESTS") == "1":
        pytest.fail(reason)
    pytest.skip(reason)


@pytest.fixture(scope="module")
def postgres_database() -> Iterator[DatabaseFactory]:
    """Provide isolated temporary databases containing migrations through a requested version."""
    admin_dsn = os.getenv("BOTJAGWAR_TEST_POSTGRES_DSN", "dbname=postgres")
    try:
        admin_connection = psycopg2.connect(admin_dsn)
    except psycopg2.Error as error:
        _postgres_unavailable(f"PostgreSQL connection unavailable: {error}")

    admin_connection.autocommit = True
    created_role = False
    database_names: set[str] = set()
    try:
        with admin_connection.cursor() as cursor:
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'botjagwar'")
            if cursor.fetchone() is None:
                try:
                    cursor.execute("CREATE ROLE botjagwar NOLOGIN")
                    created_role = True
                except psycopg2.Error as error:
                    _postgres_unavailable(f"PostgreSQL role creation unavailable: {error}")

        @contextmanager
        def create_database(last_migration: int, seed_sql: str = "") -> Iterator[connection]:
            """Create, migrate, and reliably remove one test database."""
            database_name = f"botjagwar_test_{uuid.uuid4().hex}"
            try:
                with admin_connection.cursor() as cursor:
                    cursor.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(database_name)))
            except psycopg2.Error as error:
                _postgres_unavailable(f"PostgreSQL database creation unavailable: {error}")

            database_names.add(database_name)
            test_dsn = psycopg2.extensions.make_dsn(admin_dsn, dbname=database_name)
            test_connection = psycopg2.connect(test_dsn)
            test_connection.autocommit = True
            try:
                with test_connection.cursor() as cursor:
                    cursor.execute(BASE_SCHEMA)
                    if seed_sql:
                        cursor.execute(seed_sql)
                    for version in range(6, last_migration + 1):
                        cursor.execute(MIGRATIONS[version].read_text(encoding="utf-8"))
                yield test_connection
            finally:
                test_connection.close()
                with admin_connection.cursor() as cursor:
                    cursor.execute(
                        sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(database_name))
                    )
                database_names.discard(database_name)

        yield create_database
    finally:
        for database_name in database_names:
            with admin_connection.cursor() as cursor:
                cursor.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(database_name)))
        if created_role:
            with admin_connection.cursor() as cursor:
                cursor.execute("DROP ROLE IF EXISTS botjagwar")
        admin_connection.close()


def _assert_statistics_permissions(database: connection) -> None:
    """Assert the statistics function ACL has no PUBLIC execute and grants botjagwar execute."""
    with database.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                COALESCE(bool_or(acl.grantee = 0 AND acl.privilege_type = 'EXECUTE'), false),
                COALESCE(bool_or(acl.grantee = roles.oid AND acl.privilege_type = 'EXECUTE'), false)
            FROM pg_proc AS functions
            JOIN pg_namespace AS schemas ON schemas.oid = functions.pronamespace
            CROSS JOIN pg_roles AS roles
            LEFT JOIN LATERAL aclexplode(
                COALESCE(functions.proacl, acldefault('f', functions.proowner))
            ) AS acl ON true
            WHERE schemas.nspname = 'public'
              AND functions.proname = 'atlas_dashboard_statistics'
              AND pg_get_function_identity_arguments(functions.oid) = 'p_language_limit integer'
              AND roles.rolname = 'botjagwar'
            GROUP BY roles.oid
            """
        )
        assert cursor.fetchone() == (False, True)


def _statistics_row(database: connection, period: str) -> tuple[int, list[dict[str, object]]]:
    """Return entry and translation counts for one statistics period."""
    with database.cursor() as cursor:
        cursor.execute(
            """
            SELECT entry_count, translated_languages
            FROM public.atlas_dashboard_statistics()
            WHERE period = %s
            """,
            (period,),
        )
        row = cursor.fetchone()
    assert row is not None
    return row


def test_migration_006_returns_six_utc_periods_and_restricted_permissions(
    postgres_database: DatabaseFactory,
) -> None:
    """Migration 006 exposes six UTC-derived periods through a restricted function."""
    with postgres_database(6, "") as database:
        with database.cursor() as cursor:
            cursor.execute("SET TIME ZONE 'Pacific/Auckland'")
            cursor.execute(
                """
                SELECT period, period_start, period_end, generated_at
                FROM public.atlas_dashboard_statistics()
                """
            )
            rows = cursor.fetchall()

        assert [row[0] for row in rows] == [
            "last_day",
            "last_7_days",
            "last_week",
            "last_month",
            "year_to_date",
            "last_year",
        ]
        generated_at = rows[0][3].astimezone(timezone.utc)
        periods = {
            period: (start.astimezone(timezone.utc), end.astimezone(timezone.utc))
            for period, start, end, _generated_at in rows
        }
        assert all(row[3].astimezone(timezone.utc) == generated_at for row in rows)
        assert periods["last_day"] == (generated_at - timedelta(days=1), generated_at)
        assert periods["last_7_days"] == (generated_at - timedelta(days=7), generated_at)
        last_week_start, last_week_end = periods["last_week"]
        assert last_week_end.weekday() == 0
        assert last_week_end.time() == datetime.min.time()
        assert last_week_end - last_week_start == timedelta(days=7)
        last_month_start, last_month_end = periods["last_month"]
        assert last_month_start.day == last_month_end.day == 1
        assert last_month_start.time() == last_month_end.time() == datetime.min.time()
        year_to_date_start, year_to_date_end = periods["year_to_date"]
        assert (year_to_date_start.month, year_to_date_start.day, year_to_date_start.hour) == (1, 1, 0)
        assert year_to_date_end == generated_at
        last_year_start, last_year_end = periods["last_year"]
        assert (last_year_start.month, last_year_start.day, last_year_start.hour) == (1, 1, 0)
        assert last_year_end.year == last_year_start.year + 1
        _assert_statistics_permissions(database)


def test_migration_007_generates_immutable_created_at_and_preserves_legacy_rows(
    postgres_database: DatabaseFactory,
) -> None:
    """Migration 007 avoids legacy rewrites and owns all new creation times."""
    seed_sql = """
        INSERT INTO public.word (id, date_changed, word, language) VALUES
            (1, TIMESTAMPTZ '2020-03-04 05:06:07+00', 'known', 'en'),
            (2, NULL, 'unknown', 'fr');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute("SELECT id, created_at FROM public.word ORDER BY id")
            legacy_rows = cursor.fetchall()
            assert legacy_rows == [(1, None), (2, None)]

            entry_count, _translated_languages = _statistics_row(database, "last_year")
            assert entry_count == 0

            cursor.execute(
                """
                INSERT INTO public.word (id, date_changed, created_at, word, language)
                VALUES (3, now(), TIMESTAMPTZ '2000-01-01 00:00:00+00', 'new', 'de')
                RETURNING created_at, statement_timestamp()
                """
            )
            created_at, statement_time = cursor.fetchone()
            assert created_at == statement_time

            with pytest.raises(psycopg2.Error) as error:
                cursor.execute("UPDATE public.word SET created_at = TIMESTAMPTZ '2001-01-01 00:00:00+00' WHERE id = 3")
            assert error.value.pgcode == "22000"

            cursor.execute("SELECT created_at FROM public.word WHERE id = 3")
            assert cursor.fetchone()[0] == created_at


def test_migration_007_counts_new_translation_activity_not_old_entries_and_deduplicates_words(
    postgres_database: DatabaseFactory,
) -> None:
    """New Malagasy links for an old word are activity, but multiple links count one translated word."""
    seed_sql = """
        INSERT INTO public.language (iso_code, english_name, malagasy_name)
        VALUES ('en', 'English', 'Anglisy');
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, statement_timestamp() - interval '30 days', 'old', 'en');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO public.definitions (id, definition, definition_language) VALUES
                    (1, 'voalohany', 'mg'),
                    (2, 'faharoa', 'mg');
                INSERT INTO public.dictionary (word, definition) VALUES (1, 1), (1, 2);
                """
            )
            cursor.execute(
                """
                SELECT cause, count(*)
                FROM public.events_malagasy_translation_created
                GROUP BY cause
                """
            )
            assert cursor.fetchall() == [("dictionary_insert", 2)]

        entry_count, translated_languages = _statistics_row(database, "last_day")
        assert entry_count == 0
        assert translated_languages == [
            {
                "language": "en",
                "english_name": "English",
                "malagasy_name": "Anglisy",
                "translated_entries": 1,
            }
        ]


def test_migration_007_records_definition_reclassification(
    postgres_database: DatabaseFactory,
) -> None:
    """Changing an already-linked definition to Malagasy emits translation activity."""
    seed_sql = """
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, statement_timestamp() - interval '30 days', 'old', 'fr');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO public.definitions (id, definition, definition_language)
                VALUES (1, 'definition', 'fr');
                INSERT INTO public.dictionary (word, definition) VALUES (1, 1);
                """
            )
            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 0

            cursor.execute("UPDATE public.definitions SET definition_language = 'mg' WHERE id = 1")
            cursor.execute(
                """
                SELECT word_id, definition_id, source_language, cause
                FROM public.events_malagasy_translation_created
                """
            )
            assert cursor.fetchone() == (1, 1, "fr", "definition_reclassified")


def test_migration_007_protects_events_and_function_permissions(
    postgres_database: DatabaseFactory,
) -> None:
    """Translation events reject direct writes and retain the statistics function ACL."""
    seed_sql = """
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, statement_timestamp() - interval '30 days', 'old', 'en');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO public.definitions (id, definition, definition_language)
                VALUES (1, 'dikanteny', 'mg');
                INSERT INTO public.dictionary (word, definition) VALUES (1, 1);
                """
            )
            direct_writes = [
                """
                INSERT INTO public.events_malagasy_translation_created
                    (word_id, definition_id, source_language, cause)
                VALUES (99, 99, 'en', 'dictionary_insert')
                """,
                "UPDATE public.events_malagasy_translation_created SET source_language = 'fr' WHERE word_id = 1",
                "DELETE FROM public.events_malagasy_translation_created WHERE word_id = 1",
            ]
            for statement in direct_writes:
                with pytest.raises(psycopg2.Error) as error:
                    cursor.execute(statement)
                assert error.value.pgcode == "42501"

            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 1
        _assert_statistics_permissions(database)


def test_migration_007_uses_half_open_entry_and_event_periods(
    postgres_database: DatabaseFactory,
) -> None:
    """Last-week entry and event ranges include their start and exclude their end."""
    seed_sql = """
        INSERT INTO public.language (iso_code, english_name, malagasy_name)
        VALUES ('en', 'English', 'Anglisy');
        INSERT INTO public.word (id, date_changed, word, language) VALUES
            (1, date_trunc('week', statement_timestamp() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
                - interval '1 week', 'included', 'en'),
            (2, date_trunc('week', statement_timestamp() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC',
                'excluded', 'en');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE public.events_malagasy_translation_created DISABLE TRIGGER "
                "protect_malagasy_translation_events"
            )
            cursor.execute(
                """
                INSERT INTO public.events_malagasy_translation_created
                    (word_id, definition_id, source_language, created_at, cause)
                VALUES
                    (1, 1, 'en',
                     date_trunc('week', statement_timestamp() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
                         - interval '1 week',
                     'dictionary_insert'),
                    (2, 2, 'en',
                     date_trunc('week', statement_timestamp() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC',
                     'dictionary_insert')
                """
            )
            cursor.execute(
                "ALTER TABLE public.events_malagasy_translation_created ENABLE TRIGGER "
                "protect_malagasy_translation_events"
            )
        entry_count, translated_languages = _statistics_row(database, "last_week")
        assert entry_count == 1
        assert translated_languages[0]["language"] == "en"
        assert translated_languages[0]["translated_entries"] == 1


def test_migration_008_creates_refreshable_dashboard_statistics_materialized_view(
    postgres_database: DatabaseFactory,
) -> None:
    """Migration 008 snapshots the six dashboard periods in an owned concurrent-refreshable view."""
    with postgres_database(8, "") as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                SELECT matviewname, matviewowner
                FROM pg_matviews
                WHERE matviewname = 'atlas_dashboard_statistics_mv'
                """
            )
            assert cursor.fetchone() == ("atlas_dashboard_statistics_mv", "botjagwar")

            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE tablename = 'atlas_dashboard_statistics_mv'
                """
            )
            indexes = [row[0] for row in cursor.fetchall()]
            assert "atlas_dashboard_statistics_mv_period_idx" in indexes

            cursor.execute("SELECT count(*) FROM public.atlas_dashboard_statistics_mv")
            assert cursor.fetchone()[0] == 6

            cursor.execute("REFRESH MATERIALIZED VIEW CONCURRENTLY public.atlas_dashboard_statistics_mv")
            cursor.execute("SELECT count(*) FROM public.atlas_dashboard_statistics_mv")
            assert cursor.fetchone()[0] == 6


def test_migration_007_can_be_reapplied_without_changing_existing_events(
    postgres_database: DatabaseFactory,
) -> None:
    """Operational reapplication preserves events already captured by triggers."""
    seed_sql = """
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, statement_timestamp() - interval '30 days', 'old', 'en');
        INSERT INTO public.definitions (id, definition, definition_language)
        VALUES (1, 'dikanteny', 'mg');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute("INSERT INTO public.dictionary (word, definition) VALUES (1, 1)")
            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 1

            cursor.execute(MIGRATIONS[7].read_text(encoding="utf-8"))

            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 1


def test_migration_009_backfills_historical_translation_activity(
    postgres_database: DatabaseFactory,
) -> None:
    """Backfill restores translated languages for periods before migration 007."""
    seed_sql = """
        INSERT INTO public.language (iso_code, english_name, malagasy_name)
        VALUES ('en', 'English', 'Anglisy');
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, date_trunc('month', statement_timestamp() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
            - interval '1 month' + interval '3 days', 'old', 'en');
        INSERT INTO public.definitions (id, definition, definition_language)
        VALUES (1, 'dikanteny', 'mg');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute("ALTER TABLE public.dictionary DISABLE TRIGGER capture_malagasy_translation_link")
            cursor.execute("INSERT INTO public.dictionary (word, definition) VALUES (1, 1)")
            cursor.execute("ALTER TABLE public.dictionary ENABLE TRIGGER capture_malagasy_translation_link")
            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 0

            cursor.execute(MIGRATIONS[9].read_text(encoding="utf-8"))

            cursor.execute(
                """
                SELECT word_id, definition_id, source_language, cause
                FROM public.events_malagasy_translation_created
                """
            )
            assert cursor.fetchone() == (1, 1, "en", "dictionary_insert")

        _entry_count, translated_languages = _statistics_row(database, "last_month")
        assert translated_languages == [
            {
                "language": "en",
                "english_name": "English",
                "malagasy_name": "Anglisy",
                "translated_entries": 1,
            }
        ]


def test_migration_009_is_idempotent_and_preserves_trigger_captured_events(
    postgres_database: DatabaseFactory,
) -> None:
    """Re-running the backfill neither duplicates rows nor loses captured events."""
    seed_sql = """
        INSERT INTO public.language (iso_code, english_name, malagasy_name)
        VALUES ('en', 'English', 'Anglisy');
        INSERT INTO public.word (id, date_changed, word, language)
        VALUES (1, statement_timestamp() - interval '30 days', 'old', 'en');
        INSERT INTO public.definitions (id, definition, definition_language)
        VALUES (1, 'dikanteny', 'mg');
    """
    with postgres_database(7, seed_sql) as database:
        with database.cursor() as cursor:
            cursor.execute("ALTER TABLE public.dictionary DISABLE TRIGGER capture_malagasy_translation_link")
            cursor.execute("INSERT INTO public.dictionary (word, definition) VALUES (1, 1)")
            cursor.execute("ALTER TABLE public.dictionary ENABLE TRIGGER capture_malagasy_translation_link")

            cursor.execute(MIGRATIONS[9].read_text(encoding="utf-8"))
            cursor.execute(MIGRATIONS[9].read_text(encoding="utf-8"))
            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 1

            cursor.execute("INSERT INTO public.dictionary (word, definition) VALUES (1, 1)")
            cursor.execute("SELECT count(*) FROM public.events_malagasy_translation_created")
            assert cursor.fetchone()[0] == 2


def test_migration_010_stores_and_samples_half_hour_page_check_scores(
    postgres_database: DatabaseFactory,
) -> None:
    """Migration 010 exposes bounded score history while retaining every snapshot row."""
    with postgres_database(10, "") as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                SELECT tablename, tableowner
                FROM pg_tables
                WHERE schemaname = 'public'
                  AND tablename = 'page_check_statistics_snapshots'
                """
            )
            assert cursor.fetchone() == ("page_check_statistics_snapshots", "botjagwar")

            cursor.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = 'public'
                  AND tablename = 'page_check_statistics_snapshots'
                """
            )
            indexes = {row[0] for row in cursor.fetchall()}
            assert "page_check_statistics_snapshots_history_idx" in indexes

            cursor.execute(
                """
                WITH snapshots AS (
                    SELECT
                        generate_series(0, 4) AS sequence,
                        date_trunc('hour', statement_timestamp())
                            - generate_series(0, 4) * interval '30 minutes' AS snapshot_at
                )
                INSERT INTO public.page_check_statistics_snapshots (
                    language, snapshot_at, period, generated_at, period_start, period_end,
                    retention_limit, retained_job_count, job_count, checked_count,
                    assessable_count, good_count, fixed_count, unverifiable_count,
                    error_count, good_percentage, grade
                )
                SELECT
                    'mg',
                    snapshot_at,
                    'last_7_days',
                    snapshot_at + interval '1 minute',
                    snapshot_at - interval '7 days',
                    snapshot_at + interval '1 minute',
                    200,
                    12,
                    12,
                    10,
                    8,
                    6,
                    2,
                    1,
                    1,
                    75.0,
                    'C'
                FROM snapshots
                """
            )
            cursor.execute(
                "SELECT max(snapshot_at) FROM public.page_check_statistics_snapshots"
            )
            latest_snapshot = cursor.fetchone()[0]
            cursor.execute(
                """
                SELECT snapshot_at, good_percentage, retained_job_count, retention_limit
                FROM public.page_check_score_history('mg', 'last_7_days', 2)
                """
            )
            history = cursor.fetchall()
            assert len(history) == 2
            assert history == sorted(history, key=lambda row: row[0])
            assert history[-1][0] == latest_snapshot
            assert history[-1][1:] == (75, 12, 200)

            cursor.execute(
                """
                SELECT has_function_privilege(
                    'botjagwar',
                    'public.page_check_score_history(text,text,integer)',
                    'EXECUTE'
                )
                """
            )
            assert cursor.fetchone() == (True,)

            with pytest.raises(psycopg2.Error) as error:
                cursor.execute("SELECT * FROM public.page_check_score_history('mg', 'invalid', 20)")
            assert error.value.pgcode == "22023"


def test_migration_011_recalculates_scores_over_all_jobs(
    postgres_database: DatabaseFactory,
) -> None:
    """Migration 011 includes unfinished and unassessable jobs in saved scores."""
    with postgres_database(10, "") as database:
        with database.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO public.page_check_statistics_snapshots (
                    language, snapshot_at, period, generated_at, period_start, period_end,
                    retention_limit, retained_job_count, job_count, checked_count,
                    assessable_count, good_count, fixed_count, unverifiable_count,
                    error_count, good_percentage, grade
                ) VALUES
                    (
                        'mg', '2026-08-19 12:00:00+00', 'today',
                        '2026-08-19 12:01:00+00', '2026-08-19 00:00:00+00',
                        '2026-08-19 12:01:00+00', 200, 12, 12, 10, 8, 6, 2, 1, 1, 75.0, 'C'
                    ),
                    (
                        'mg', '2026-08-19 12:30:00+00', 'today',
                        '2026-08-19 12:31:00+00', '2026-08-19 00:00:00+00',
                        '2026-08-19 12:31:00+00', 200, 1, 1, 1, 0, 0, 0, 0, 1, NULL, NULL
                    )
                """
            )
            cursor.execute(MIGRATIONS[11].read_text(encoding="utf-8"))
            cursor.execute(
                """
                SELECT good_percentage, grade
                FROM public.page_check_statistics_snapshots
                ORDER BY snapshot_at
                """
            )

            assert cursor.fetchall() == [(50, "E"), (0, "E")]

            with pytest.raises(psycopg2.Error):
                cursor.execute(
                    """
                    INSERT INTO public.page_check_statistics_snapshots (
                        language, snapshot_at, period, generated_at, period_start, period_end,
                        retention_limit, retained_job_count, job_count, checked_count,
                        assessable_count, good_count, fixed_count, unverifiable_count,
                        error_count, good_percentage, grade
                    ) VALUES (
                        'en', '2026-08-19 12:00:00+00', 'today',
                        '2026-08-19 12:01:00+00', '2026-08-19 00:00:00+00',
                        '2026-08-19 12:01:00+00', 200, 1, 1, 1, 0, 0, 0, 0, 1, NULL, NULL
                    )
                    """
                )
