from .en import (
    POSSESSIVENESS as POSSESSIVENESS,
    NUMBER as NUMBER,
    PERSONS as PERSONS,
    DEFINITENESS as DEFINITENESS,
    GENDER as GENDER,
    VOICE as VOICE,
    MOOD as MOOD,
    CASES as CASES,
    TENSE as TENSE,
)
