import type { Translate } from "./i18n";
import type { BilingualMessage, BilingualRelationDefinition, FieldDefinition, RelationCatalog, RelationDefinition } from "./types";

const text = (name: string, required = false, kind: FieldDefinition["kind"] = "text"): FieldDefinition => ({
  name,
  required,
  kind,
});

const number = (name: string, required = false, readOnly = false): FieldDefinition => ({
  name,
  required,
  readOnly,
  kind: "number",
});

const dateTime = (name: string, required = false, readOnly = false): FieldDefinition => ({ name, required, readOnly, kind: "datetime" });

const message = (malagasy: string, english: string): BilingualMessage => ({ malagasy, english });

const bilingualTableRelations: BilingualRelationDefinition[] = [
  {
    name: "word",
    label: message("Teny", "Words"),
    group: message("Rakibolana", "Dictionary"),
    kind: "table",
    description: message("Teny fototra, kaodim-piteny ary sokajin-teny ao amin'ny rakibolana.", "Dictionary headwords, language codes, and parts of speech."),
    identity: ["id"],
    searchFields: ["word", "language", "part_of_speech"],
    defaultOrder: "id.desc",
    fields: [number("id", false, true), dateTime("created_at", false, true), dateTime("date_changed"), text("word", true), text("language", true), text("part_of_speech", true)],
  },
  {
    name: "definitions",
    label: message("Famaritana", "Definitions"),
    group: message("Rakibolana", "Dictionary"),
    kind: "table",
    description: message("Lahatsoratry ny famaritana amin'ny fiteny loharano sy kendrena, miaraka amin'ny embeddings raha misy.", "Definition text in source and target languages, with optional embeddings."),
    identity: ["id"],
    searchFields: ["definition", "definition_language"],
    defaultOrder: "id.desc",
    fields: [
      number("id", false, true),
      dateTime("date_changed"),
      text("definition", true, "textarea"),
      text("definition_language", true),
      { name: "definition_vector", readOnly: true, hiddenFromList: true, kind: "json" },
    ],
  },
  {
    name: "dictionary",
    label: message("Rohin'ny teny sy famaritana", "Word-definition links"),
    group: message("Rakibolana", "Dictionary"),
    kind: "table",
    description: message("Rohy many-to-many mampifandray ny teny sy ny famaritana.", "Many-to-many associations connecting words to definitions."),
    identity: ["word", "definition"],
    defaultOrder: "word.desc",
    fields: [number("word", true), number("definition", true)],
  },
  {
    name: "language",
    label: message("Fiteny", "Languages"),
    group: message("Rakibolana", "Dictionary"),
    kind: "table",
    description: message("Katalaogin'ny kaodim-piteny sy angona momba ny fihaviany.", "Language code catalog and ancestry data."),
    identity: ["iso_code"],
    searchFields: ["iso_code", "english_name", "malagasy_name"],
    defaultOrder: "iso_code.asc",
    fields: [text("iso_code", true), text("english_name"), text("malagasy_name"), text("language_ancestor")],
  },
  {
    name: "additional_word_information",
    label: message("Angona fanampin'ny teny", "Additional word data"),
    group: message("Rakibolana", "Dictionary"),
    kind: "table",
    description: message("Loharano, fanononana, ohatra ary metadata hafa voasokajy momba ny teny.", "References, pronunciations, examples, and other typed word metadata."),
    identity: ["word_id", "type", "information"],
    searchFields: ["type", "information"],
    defaultOrder: "word_id.desc",
    fields: [number("word_id", true), text("type", true), text("information", true, "textarea")],
  },
  {
    name: "mt_translated_definition",
    label: message("Dikanteny milina", "Machine translations"),
    group: message("Fandikan-teny", "Translation"),
    kind: "table",
    description: message("Famaritana nadikan'ny milina sy ny fomba namokarana azy.", "Machine-translated definitions and the methods that produced them."),
    identity: ["id", "definition", "definition_language", "method"],
    searchFields: ["definition", "definition_language", "method"],
    defaultOrder: "date_changed.desc",
    fields: [number("id", true), dateTime("date_changed"), text("definition", true, "textarea"), text("definition_language", true), text("method", true)],
  },
  {
    name: "nllb_translations",
    label: message("Cache NLLB", "NLLB cache"),
    group: message("Fandikan-teny", "Translation"),
    kind: "table",
    description: message("Dikantenin'ny fehezanteny novokarin'ny NLLB izay azo ampiasaina indray.", "Reusable sentence translations generated by NLLB."),
    identity: ["source_language", "target_language", "sentence"],
    searchFields: ["source_language", "target_language", "sentence", "translation"],
    defaultOrder: "source_language.asc",
    fields: [
      text("source_language", true),
      text("target_language", true),
      text("sentence", true, "textarea"),
      text("translation", false, "textarea"),
      { name: "sentence_vector", readOnly: true, hiddenFromList: true, kind: "json" },
    ],
  },
  {
    name: "template_translations",
    label: message("Dikanteny template", "Template translations"),
    group: message("Fandikan-teny", "Translation"),
    kind: "table",
    description: message("Fampifandraisana ny template Wiktionary loharano sy kendrena.", "Mappings between source and target Wiktionary templates."),
    identity: ["source_template", "source_language", "target_template", "target_language"],
    searchFields: ["source_template", "target_template", "source_language", "target_language"],
    defaultOrder: "source_template.asc",
    fields: [text("source_template"), text("target_template"), text("source_language"), text("target_language")],
  },
  {
    name: "translation_method",
    label: message("Fomba fandikan-teny", "Translation methods"),
    group: message("Fandikan-teny", "Translation"),
    kind: "table",
    description: message("Rakitra momba ny niavian'ny dikantenin'ny teny sy famaritana.", "Provenance records for word-definition translations."),
    identity: ["word", "definition", "translation_method"],
    searchFields: ["translation_method"],
    defaultOrder: "word.desc",
    fields: [number("word", true), number("definition", true), text("translation_method", true)],
  },
  {
    name: "new_associations",
    label: message("Rohy vaovao", "New associations"),
    group: message("Fizotran'ny asa", "Workflow"),
    kind: "table",
    description: message("Filaharan'ireo rohin'ny teny sy famaritana vao noforonina.", "Queue of newly created word-definition associations."),
    identity: ["word", "definition", "associated_on"],
    defaultOrder: "associated_on.desc",
    fields: [
      number("word", true),
      number("definition", true),
      dateTime("associated_on"),
      { name: "status", required: true, kind: "select", options: ["PENDING", "PROCESSING", "DONE", "FAILED"] },
    ],
  },
  {
    name: "events_definition_changed",
    label: message("Fanovana famaritana", "Definition changes"),
    group: message("Fanaraha-maso", "Audit"),
    kind: "table",
    description: message("Tranga fanovana famaritana sy satan'ny fanodinana azy.", "Definition change events and processing status."),
    identity: ["id"],
    searchFields: ["old_definition", "new_definition", "commentary"],
    defaultOrder: "change_datetime.desc",
    fields: [
      number("id", false, true),
      number("definition_id", true),
      dateTime("change_datetime", true),
      { name: "status", required: true, kind: "select", options: ["PENDING", "PROCESSING", "DONE", "FAILED"] },
      dateTime("status_datetime", true),
      text("old_definition", true, "textarea"),
      text("new_definition", true, "textarea"),
      text("commentary", false, "textarea"),
    ],
  },
  {
    name: "events_rel_definition_word_deleted",
    label: message("Rohy voafafa", "Deleted associations"),
    group: message("Fanaraha-maso", "Audit"),
    kind: "table",
    description: message("Audit log avoaka rehefa esorina ny rohin'ny teny sy famaritana.", "Audit log emitted when word-definition links are removed."),
    identity: ["definition", "word", "date_changed"],
    defaultOrder: "date_changed.desc",
    readOnly: true,
    fields: [number("definition", true), number("word", true), { name: "date_changed", required: true, kind: "date" }, text("comment", false, "textarea")],
  },
  {
    name: "events_malagasy_translation_created",
    label: message("Dikanteny malagasy vaovao", "Malagasy translations created"),
    group: message("Fanaraha-maso", "Audit"),
    kind: "table",
    description: message("Tranga tsy azo ovaina rehefa mahazo famaritana malagasy ny teny tsy malagasy.", "Immutable events emitted when non-Malagasy entries acquire Malagasy definitions."),
    identity: ["id"],
    searchFields: ["source_language", "cause"],
    defaultOrder: "created_at.desc",
    readOnly: true,
    fields: [
      number("id", false, true),
      number("word_id", true, true),
      number("definition_id", true, true),
      text("source_language", true),
      dateTime("created_at", true, true),
      text("cause", true),
    ],
  },
];

const view = (name: string, label: BilingualMessage, group: BilingualMessage, description: BilingualMessage, kind: RelationDefinition["kind"] = "view"): BilingualRelationDefinition => ({
  name,
  label,
  group,
  description,
  kind,
  readOnly: true,
});

const bilingualViewRelations: BilingualRelationDefinition[] = [
  view("unaggregated_dictionary", message("Rakibolana tsy natambatra", "Unaggregated dictionary"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Rakitra tsotra mampifandray teny sy famaritana.", "Flat word-definition records.")),
  view("unaggregated_dictionary_with_undefined_words", message("Rakibolana misy teny tsy voafaritra", "Dictionary with undefined words"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Andalana tsotra ao amin'ny rakibolana, anisan'izany ny teny tsy misy famaritana.", "Flat dictionary rows including words without definitions.")),
  view("vw_json_dictionary", message("Rakibolana JSON", "JSON dictionary"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Teny misy famaritana mifampiditra sy metadata fanampiny.", "Words with nested definitions and additional metadata.")),
  view("word_with_additional_data", message("Teny misy angona fanampiny", "Words with additional data"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Teny miaraka amin'ny metadata voasokajy sy natambatra.", "Words with aggregated typed metadata.")),
  view("additional_word_information_by_type", message("Isan'ny metadata", "Metadata counts"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Angona fanampin'ny teny navondrona araka ny sokajy.", "Additional word information grouped by type.")),
  view("additional_word_information_types", message("Sokajin'ny metadata", "Metadata types"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Sokajy miavaka amin'ny angona fanampiny.", "Distinct additional information types.")),
  view("all_references", message("Loharano rehetra", "All references"), message("Tatitry ny rakibolana", "Dictionary reports"), message("Sanda miavaka amin'ny loharanon'ny rakibolana.", "Distinct dictionary reference values.")),
  view("most_used_definitions", message("Famaritana be mpampiasa indrindra", "Most-used definitions"), message("Tatitry ny famaritana", "Definition reports"), message("Famaritana nalahatra araka ny isan'ny teny mifandray aminy.", "Definitions ranked by associated word count.")),
  view("untranslated_most_used_definitions", message("Famaritana mbola tsy voadika", "Untranslated definitions"), message("Tatitry ny famaritana", "Definition reports"), message("Famaritana fampiasa matetika nefa tsy mbola misy dikanteny.", "Frequently used definitions without translations.")),
  view("definitions_with_repeated_subsentence", message("Ampahan-teny miverimberina", "Repeated subsentences"), message("Tatitry ny famaritana", "Definition reports"), message("Famaritana misy lahatsoratra miverimberina sy fanitsiana atolotra.", "Definitions containing repeated text and proposed fixes.")),
  view("mv_definitions_with_repeated_subsentence", message("Sary raikitry ny ampahan-teny miverimberina", "Repeated subsentences snapshot"), message("Tatitry ny famaritana", "Definition reports"), message("Tatitra materialized momba ny lahatsoratra miverimberina.", "Materialized repeated-text report."), "materialized-view"),
  view("inconsistent_definitions", message("Famaritana tsy mifanaraka", "Inconsistent definitions"), message("Tatitry ny famaritana", "Definition reports"), message("Famaritana iombonan'ny sokajin-teny tsy mifanaraka.", "Definitions shared across incompatible parts of speech.")),
  view("convergent_translations", message("Dikanteny mifanojo", "Convergent translations"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Famaritana anglisy sy frantsay mifanojo amin'ny soso-kevitra malagasy.", "English and French definitions converging on Malagasy suggestions.")),
  view("unpublished_convergent_translations_mg", message("Dikanteny mifanojo mbola tsy nivoaka", "Unpublished convergent translations"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Soso-kevitra malagasy mifanojo izay mbola tsy navoaka.", "Convergent Malagasy suggestions not yet published.")),
  view("suggested_translations_en_mg", message("Soso-kevitra avy amin'ny anglisy", "English suggestions"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Soso-kevitra handikana famaritana anglisy ho amin'ny teny malagasy.", "Suggested English-to-Malagasy definition translations."), "materialized-view"),
  view("suggested_translations_fr_mg", message("Soso-kevitra avy amin'ny frantsay", "French suggestions"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Soso-kevitra handikana famaritana frantsay ho amin'ny teny malagasy.", "Suggested French-to-Malagasy definition translations."), "materialized-view"),
  view("matview_suggested_translations_en_mg", message("Soso-kevitra anglisy natambatra", "Aggregated English suggestions"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Soso-kevitra malagasy natambatra ho an'ny famaritana anglisy.", "Aggregated Malagasy suggestions for English definitions.")),
  view("unaggregated_mt_translated_dictionary", message("Rakibolana nadikan'ny milina", "Machine-translated dictionary"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Dikanteny milina natambatra tamin'ny teny sy famaritana loharano.", "Machine translations joined with source words and definitions.")),
  view("word_with_openmt_translation", message("Teny misy OpenMT", "Words with OpenMT"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Teny misy metadata OpenMT.", "Words carrying OpenMT metadata.")),
  view("mv_word_with_openmt_translation", message("Sary raikitry ny teny OpenMT", "OpenMT words snapshot"), message("Tatitry ny fandikan-teny", "Translation reports"), message("Tatitra materialized momba ny teny OpenMT.", "Materialized OpenMT word report."), "materialized-view"),
  view("en_mg", message("Rakibolana anglisy-malagasy", "English-Malagasy dictionary"), message("Fanondranana rakibolana", "Dictionary exports"), message("Rakibolana anglisy-malagasy materialized.", "Materialized English-Malagasy dictionary."), "materialized-view"),
  view("fr_mg", message("Rakibolana frantsay-malagasy", "French-Malagasy dictionary"), message("Fanondranana rakibolana", "Dictionary exports"), message("Rakibolana frantsay-malagasy materialized.", "Materialized French-Malagasy dictionary."), "materialized-view"),
  view("vw_en_mg", message("View anglisy-malagasy", "English-Malagasy view"), message("Fanondranana rakibolana", "Dictionary exports"), message("View fanondranana anglisy-malagasy.", "English-Malagasy export view.")),
  view("vw_fr_mg", message("View frantsay-malagasy", "French-Malagasy view"), message("Fanondranana rakibolana", "Dictionary exports"), message("View fanondranana frantsay-malagasy.", "French-Malagasy export view.")),
  view("concat_dictionary", message("Rakibolana nakambana", "Concatenated dictionary"), message("Fanondranana rakibolana", "Dictionary exports"), message("Andalan'ny rakibolana nakambana sy natao materialized.", "Materialized concatenated dictionary lines."), "materialized-view"),
  view("lemma_by_language", message("Lemma isaky ny fiteny", "Lemmata by language"), message("Fanondranana rakibolana", "Dictionary exports"), message("Array lemma materialized sy navondrona araka ny fiteny.", "Materialized lemma arrays grouped by language."), "materialized-view"),
  view("json_dictionary", message("Sary raikitry ny rakibolana JSON", "JSON dictionary snapshot"), message("Fanondranana rakibolana", "Dictionary exports"), message("Payload JSON materialized an'ny rakibolana.", "Materialized JSON dictionary payloads."), "materialized-view"),
  view("db_stats", message("Fitehirizan'ny banky angona", "Database storage"), message("Rafitra", "System"), message("Haben'ny singa PostgreSQL sy tombana isan'andalana.", "PostgreSQL relation sizes and row estimates.")),
];

const localizeRelation = (relation: BilingualRelationDefinition, t: Translate): RelationDefinition => ({
  ...relation,
  label: t(relation.label.malagasy, relation.label.english),
  group: t(relation.group.malagasy, relation.group.english),
  description: t(relation.description.malagasy, relation.description.english),
});

/** Builds an isolated relation catalog localized by the supplied translator. */
export function buildRelationCatalog(t: Translate): RelationCatalog {
  const tableRelations = bilingualTableRelations.map((relation) => localizeRelation(relation, t));
  const viewRelations = bilingualViewRelations.map((relation) => localizeRelation(relation, t));
  const relations = [...tableRelations, ...viewRelations];

  return {
    tableRelations,
    viewRelations,
    relations,
    relationByName: new Map(relations.map((relation) => [relation.name, relation])),
  };
}

const defaultCatalog = buildRelationCatalog((malagasy) => malagasy);

export const tableRelations = defaultCatalog.tableRelations;
export const viewRelations = defaultCatalog.viewRelations;
export const relations = defaultCatalog.relations;

export const relationByName = defaultCatalog.relationByName;

export function relationGroups(items: RelationDefinition[] = relations): Map<string, RelationDefinition[]> {
  const groups = new Map<string, RelationDefinition[]>();
  for (const relation of items) {
    const current = groups.get(relation.group) ?? [];
    current.push(relation);
    groups.set(relation.group, current);
  }
  return groups;
}
