#!/usr/bin/env python3
"""Fetch the Atlas dashboard statistics snapshot generated by a remote Botjagwar host."""

import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from scripts.refresh_dashboard_statistics import (
        LOCK_FILENAME,
        acquire_statistics_lock,
        validate_statistics_file,
    )
    from scripts.refresh_materialized_views import configure_logging
except ModuleNotFoundError:  # Direct execution adds scripts/, not the repository root, to sys.path.
    from refresh_dashboard_statistics import (
        LOCK_FILENAME,
        acquire_statistics_lock,
        validate_statistics_file,
    )
    from refresh_materialized_views import configure_logging

LOGGER = logging.getLogger(__name__)
SOURCE_ENVIRONMENT_VARIABLE = "BOTJAGWAR_DASHBOARD_STATISTICS_SOURCE"
DEFAULT_ATLAS_STATE_DIR = Path("/var/lib/botjagwar/atlas")
STATISTICS_FILENAME = "logs/dashboard-statistics.json"
SCP_COMMAND = "scp"
SCP_TIMEOUT_SECONDS = 30


def parse_statistics_source(source: str) -> tuple[str, str]:
    """Split the host:path source into an SSH target and a remote path."""
    if ":" not in source:
        raise ValueError("Dashboard statistics source must be host:path")
    target, remote_path = source.split(":", 1)
    if not target or not remote_path:
        raise ValueError("Dashboard statistics source must be host:path")
    return target, remote_path


def copy_remote_statistics(target: str, remote_path: str, local_path: Path) -> None:
    """Copy the remote snapshot file to a local path over SCP."""
    completed = subprocess.run(
        [
            SCP_COMMAND,
            "-q",
            "-o",
            "BatchMode=yes",
            "-o",
            "ConnectTimeout=10",
            f"{target}:{remote_path}",
            str(local_path),
        ],
        capture_output=True,
        text=True,
        timeout=SCP_TIMEOUT_SECONDS,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"Could not fetch dashboard statistics from {target}:{remote_path} "
            f"({completed.stderr.strip() or completed.stdout.strip()})"
        )


def fetch_dashboard_statistics(source: str, output_path: Path) -> int:
    """Copy the remote snapshot through a temporary file and atomically replace the local one."""
    target, remote_path = parse_statistics_source(source)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lock_file = acquire_statistics_lock(output_path.parent / LOCK_FILENAME)
    if lock_file is None:
        try:
            validate_statistics_file(output_path)
        except (OSError, ValueError, RuntimeError) as exc:
            raise RuntimeError(
                "Another dashboard statistics refresh is running and no valid snapshot exists."
            ) from exc
        LOGGER.info("Another dashboard statistics refresh is already running; keeping the valid snapshot.")
        return 0
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{output_path.name}.", dir=output_path.parent
        )
        os.close(descriptor)
        try:
            copy_remote_statistics(target, remote_path, Path(temporary_name))
            validate_statistics_file(Path(temporary_name))
            os.chmod(temporary_name, 0o644)
            os.replace(temporary_name, output_path)
        finally:
            if os.path.exists(temporary_name):
                os.unlink(temporary_name)
    finally:
        lock_file.close()
    LOGGER.info("Wrote dashboard statistics snapshot from %s to %s.", source, output_path)
    return 1


def main() -> int:
    """Run the configured remote dashboard statistics fetch job."""
    configure_logging()
    source = os.environ.get(SOURCE_ENVIRONMENT_VARIABLE)
    if not source:
        LOGGER.error("%s is not set.", SOURCE_ENVIRONMENT_VARIABLE)
        return 1
    state_dir = Path(os.environ.get("BOTJAGWAR_ATLAS_STATE_DIR", DEFAULT_ATLAS_STATE_DIR))
    try:
        fetch_dashboard_statistics(source, state_dir / STATISTICS_FILENAME)
    except (ValueError, RuntimeError, OSError, subprocess.TimeoutExpired):
        LOGGER.exception("Dashboard statistics fetch did not complete successfully.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
